// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6oMOcXek62nH6RV9k6VaZgqBYa2Kzkrc',
    appId: '1:712279850389:web:29bc5c9ed97517beab4a9c',
    messagingSenderId: '712279850389',
    projectId: 'fitai-app-38d91',
    authDomain: 'fitai-app-38d91.firebaseapp.com',
    storageBucket: 'fitai-app-38d91.firebasestorage.app',
    measurementId: 'G-KBTKXVW06H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3kXlVFgVkIlylgxsQwG03rZc9jJKGpN0',
    appId: '1:712279850389:android:fe1d970390c884b9ab4a9c',
    messagingSenderId: '712279850389',
    projectId: 'fitai-app-38d91',
    storageBucket: 'fitai-app-38d91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf5i5rKuOYbeLcVeGsro-liVbWguvI250',
    appId: '1:712279850389:ios:1bf32d1585f8cae8ab4a9c',
    messagingSenderId: '712279850389',
    projectId: 'fitai-app-38d91',
    storageBucket: 'fitai-app-38d91.firebasestorage.app',
    iosBundleId: 'com.example.fitaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf5i5rKuOYbeLcVeGsro-liVbWguvI250',
    appId: '1:712279850389:ios:1bf32d1585f8cae8ab4a9c',
    messagingSenderId: '712279850389',
    projectId: 'fitai-app-38d91',
    storageBucket: 'fitai-app-38d91.firebasestorage.app',
    iosBundleId: 'com.example.fitaiApp',
  );
}
